#!/bin/bash

# Clone the GitHub repository
git clone https://github.com/KIM-JS-95/Air_Scheduler.git
cd Air_Scheduler

# Build Docker images
docker-compose build

# Start Docker containers
docker-compose up -d

# Check the status of Docker containers
docker-compose ps

# Display the logs of Docker containers
docker-compose logs
