version: '3.0'
services:
  schedules:
    container_name: flight_schedules
    image: baugh248730/flight_schedules:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9090:9090
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: 1q2w3e4r
      MYSQL_PORT: 3307
    restart: unless-stopped
    depends_on:
      - mysql
      - ocr
  mysql:
    container_name: mysql
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: testdb
      MYSQL_ROOT_PASSWORD: 1q2w3e4r
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 3307:3306

  ocr:
    container_name: python_ocr
    image: baugh248730/table-detection:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    restart: unless-stopped
    depends_on:
      - mysql
volumes:
  mysql_data: